### ISSUE TITLE
Provide alternative SendGazeReportXX() method without timestamp

### ISSUE THREAD

**Issue by jatinsha** [MSREnable/GazeHid#3]
SendGazeReportUm(long X, long Y, unsigned long long timestamp);
SendGazeReportPixel(long X, long Y, unsigned long long timestamp);

The current SendGazeReportXX methods expect timestamp to be supplied by the user. In certain scenarios, the user may not have timestamps and should be able to use the API where the API itself calculates the timestamps internally.

**Comment by jatinsha** [comment]
I am assuming that the timestamp is in milliseconds but it would be good to have a short description (or a more descriptive name). E.g. timestamp_ms_from_epoch, timestamp_ms etc.

**Comment by joncamp** [comment]
![image](https://user-images.githubusercontent.com/11506084/110162379-833ebc00-7da3-11eb-80c6-1fe01e1f0873.png)
Good point, clarity would definitely help in this case. in reality I believe under the covers it is mostly ignored as long as it is positive and increasing, but we should do the right thing.

**Comment by joncamp** [comment]
Sending 0 will automatically generate a timestamp.
