### ISSUE TITLE
`GazeHidTest`: Unable to open gaze HID: `HidDevice.FromIdAsync` returns `null`

### ISSUE THREAD

**Issue by lostmsu** [MSREnable/GazeHid#6]
I had to manually go to system Settings -> Privacy -> Eye tracker and enable it for GazeHidTest in order for it to appear in `DeviceInformation.FindAllAsync(selector)` (without this action the returned array was emtpy).

Still can not open the device itself. In [this line](https://github.com/MSREnable/GazeHid/blob/afc97c83ff2bef0caadce82b9ab23d71f50dc00e/GazeHidTest/MainPage.xaml.cs#L121) `_eyeTracker` is `null`.

I also tried to do `HidDevice.FromAsyncId` from non-sandboxed app (e.g. desktop WPF) with the same result. When I manually try to call `CreateFile` (via a [3rd party library](https://github.com/mikeobrien/HidLibrary)) on the HID device I get explicit Access Denied error, even when the app is launched as administrator.

Is opening eye tracker HID device a supported scenario? If not, is there any other way to read coordinate reports from a non-UWP app (desktop WPF or Win32)?

### Environment
OS: Windows 10 21H2 (19044.1706)
Hardware: Tobii Eye Tracker
![image](https://user-images.githubusercontent.com/239520/170538153-d33765e5-873a-4c47-8bf5-846326d143c5.png)

P.S. Eye control feature in Windows works

**Comment by joncamp** [comment]
Thanks for your interest in these features. I just want to be sure I am tracking what you are trying to do. Based on the above screenshot it appears that you are using a Tobii eye tracker? If so, which model and divers are you using?

**Comment by lostmsu** [comment]
@lostmsu I am using the old EyeX. I can read the data using their legacy library, but I was interested in doing it in a device-independent way.

**Comment by joncamp** [comment]
Excellent - and to further verify - you are able to access eye tracking using UWP based solutions (Eye Control for Windows, Eyes First Games, or custom code)? If the eye tracker isn't working with HID at all using UWP, then it's likely a driver issue. There have been times where the tobii driver's support of HID was having issues.

**Comment by lostmsu** [comment]
The `GazeTracing` app, that uses `GazeInputSourcePreview` from this repo works fine, so is Windows "Eye control" feature in settings.

**Comment by joncamp** [comment]
Ok - so it sounds like the HID support in the driver itself is working, as well as the underlying windows HID support that connects to UWP. Currently there is no support for non-UWP HID access through the Windows APIs, though I encourage you to submit feedback via the Feeback Hub app. https://github.com/microsoft/WindowsAppSDK/issues/432 tracks one such proposal, so I encourage you to comment on that as well.

There may also be a driver level setting preventing access - consider reaching out to Tobii developer support and see what they say.
